name: Build and Push Docker

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - 'release-*'
      - develop
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
